backend:
  name: github
  repo: fizal619/saffron
  branch: master
  site_domain: saffrongy.netlify.app

local_backend: true

media_folder: "images/upload"

collections:
  - label: Pages
    name: pages
    files:
      - label: Our Story
        name: our-story
        file: story.md
        preview_path: our-story
        fields:
          - label: Title
            name: title
            widget: string
          - label: Content
            name: body
            widget: markdown

  - name: products # Used in routes, e.g., /admin/collections/blog
    label: Product # Used in the UI
    folder: "_products/" # The path to the folder where the documents are stored
    preview_path: order-online
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: Name, name: title, widget: string}
      - {label: Price, name: price, widget: string}
      - label: Image
        widget: image
        name: image
      - label: Options
        name: options
        widget: list
        allow_add: true
        default: []
        required: false
      - {label: "Description", name: "description", widget: "string", required: false}

  - name: categories
    label: Category
    folder: "_categories/"
    preview_path: order-online
    create: true
    fields:
      - label: Display Name
        name: title
        required: true
      - label: "Hide Category"
        name: "hidden"
        widget: "boolean"
        default: false
      - label: Products
        name: products
        widget: relation
        collection: products
        value_field: title
        multiple: true
        search_fields: [ "title" ]
        display_fields: [ "title" ]

  - name: testimonials
    label: Testimonial
    folder: "_testimonials/"
    preview_path: /
    create: true
    fields:
      - label: Customer Name
        name: title
        required: true
      - label: Content
        name: body
        widget: markdown
        required: true

